image: alpine:latest

stages:
  - build
  - test
  - deploy

before_script:
  - echo "I am before script "

after_script:
  - echo "I am from after scriiiipt !!"

build step 1:
  stage: build
  script:
    - echo "I am from build step 1"
  tags:
    - mac

build step 2:
  stage: build
  script:
    - echo "I am from build step 2"
  tags:
    - mac

test step 1:
  stage: test
  script:
    - echo "I am from the test sep 1"
  tags:
    - debian

deploy:
  stage: deploy
  script:
    - echo "I am  deploying somthing !!!!"
  tags:
    - mac
