# pull a docker image from dockerhub
default:
  image: docker:stable
  tags:
    - "hamza-runner-ubuntu"

variables:
  CONTAINER_REGISTRY: "registry.gitlab.com"
  CI_DOCKER_REPO: $CONTAINER_REGISTRY/hamza-webdev/myawesome-project-sf-git-hooks-bash/nginx:latest

stages:
  - build docker image
  - push docker image
before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI _REGISTRY_PASSWORD

build and push:
  stage: build docker image
  script:
    - docker build -t $CI_DOCKER_REPO:$CI_COMMIT_SHORT_SHA -f Dockerfile .
    - docker push $CI_DOCKER_REPO:$CI_COMMIT_SHORT_SHA
  only:
    refs:
      - merge_requests
